#include<iostream>

using namespace std;

int main(){

int A=1, B=2, C=3,*P1,*P2; //VARIABLES A,B,C Y LOS APUNTADORES P1 Y P2

P1=&A;//P1(MEMORIA) VALOR DE MEMORIA DE A
P2=&C;//P2(MEMORIA) VALOR DE MEMORIA DE C
*P1=(*P2)++;//VALOR DE VARIABLE DE P1 IGUAL AL VALOR DE VARIABLE DE P2 MAS 1
P1=P2; //VALOR (MEMORIA) GUARDADO EN P1 IGUAL AL VALOR GUARDADO EN P2 (MEMORIA)
P2=&B; //P2 (MEMORIA) VALOR DE MEMORIA DE B
*P1-=*P2;//VALOR VARIABLE P1 IGUAL AL VALOR DE P1 MENOS EL VALOR DE P2
++*P2;//VALOR DE P2 MAS 1
*P1*=*P2;//VALOR DE P1 IGUAL AL VALOR DE P1 POR VALOR DE P2
A=++*P2**P1;//A IGUAL A VALOR DE P2 MAS 1, POR VALOR DE P1
P1=&A; //P1 (MEMORIA) IGUAL AL VALOR DE MEMORIA DE A
*P2=*P1/=*P2;//VALOR DE P2 IGAULA AL VALOR DE P1, IGUAL AL VALOR DE P1 DIVIDIDO POR EL VALOR DE P2

    return 0;
}